import * as THREE from "three";
import type { BoneName } from "./rig";

/**
 * Hand-authored animation clips.
 *
 * Each clip is a set of real `QuaternionKeyframeTrack`s on bone rotations plus
 * a `VectorKeyframeTrack` on the hips for vertical bob — the same data an
 * imported glTF would carry, generated by sampling gait functions at a fixed
 * rate. Writing them as functions rather than baked numbers means the walk and
 * run cycles stay in phase with each other by construction, which is what lets
 * them cross-fade without the legs scissoring.
 *
 * All clips are **in place**: the controller owns world position, so the feet
 * are driven to match ground speed by the mixer's timeScale instead of by root
 * motion (see `useCharacterAnimation`).
 *
 * Convention: arms and legs hang down -Y, so a positive X rotation swings a
 * limb forward.
 */
const SAMPLES = 24;

type Sampler = (phase: number) => THREE.Euler;

/** Sample a rotation function into a quaternion track for one bone. */
function rotationTrack(bone: BoneName, duration: number, sample: Sampler): THREE.QuaternionKeyframeTrack {
  const times: number[] = [];
  const values: number[] = [];
  const q = new THREE.Quaternion();
  for (let i = 0; i <= SAMPLES; i++) {
    const phase = i / SAMPLES;
    times.push(phase * duration);
    q.setFromEuler(sample(phase));
    values.push(q.x, q.y, q.z, q.w);
  }
  return new THREE.QuaternionKeyframeTrack(`${bone}.quaternion`, times, values);
}

function positionTrack(
  bone: BoneName,
  duration: number,
  rest: THREE.Vector3,
  sample: (phase: number) => THREE.Vector3,
): THREE.VectorKeyframeTrack {
  const times: number[] = [];
  const values: number[] = [];
  const v = new THREE.Vector3();
  for (let i = 0; i <= SAMPLES; i++) {
    const phase = i / SAMPLES;
    times.push(phase * duration);
    v.copy(rest).add(sample(phase));
    values.push(v.x, v.y, v.z);
  }
  return new THREE.VectorKeyframeTrack(`${bone}.position`, times, values);
}

const TAU = Math.PI * 2;
/** Rest position of the hips, mirrored from the rig definition. */
const HIPS_REST = new THREE.Vector3(0, 0.86, 0);

/**
 * Shared gait shape. `swing` is the peak limb rotation and `lean` the forward
 * pitch of the spine; walk and run differ mostly in those two numbers, which
 * is why they blend cleanly.
 */
function gaitClip(name: string, opts: {
  duration: number;
  swing: number;
  kneeBend: number;
  armSwing: number;
  elbowBend: number;
  lean: number;
  bob: number;
}): THREE.AnimationClip {
  const { duration, swing, kneeBend, armSwing, elbowBend, lean, bob } = opts;
  const tracks: THREE.KeyframeTrack[] = [];

  for (const [side, sign] of [["L", 1], ["R", -1]] as const) {
    // Legs are half a cycle apart.
    const legPhase = sign > 0 ? 0 : 0.5;
    tracks.push(
      rotationTrack(`upperLeg${side}` as BoneName, duration, (p) =>
        new THREE.Euler(Math.sin((p + legPhase) * TAU) * swing, 0, 0),
      ),
    );
    tracks.push(
      // The knee only bends one way, and most during the swing-through.
      rotationTrack(`lowerLeg${side}` as BoneName, duration, (p) => {
        const s = Math.sin((p + legPhase) * TAU + Math.PI * 0.6);
        return new THREE.Euler(-kneeBend * Math.max(0, s) - kneeBend * 0.12, 0, 0);
      }),
    );
    tracks.push(
      rotationTrack(`foot${side}` as BoneName, duration, (p) =>
        new THREE.Euler(Math.sin((p + legPhase) * TAU + Math.PI * 0.35) * swing * 0.35, 0, 0),
      ),
    );
    // Arms counter-swing against the legs.
    tracks.push(
      rotationTrack(`upperArm${side}` as BoneName, duration, (p) =>
        new THREE.Euler(-Math.sin((p + legPhase) * TAU) * armSwing, 0, sign * 0.07),
      ),
    );
    tracks.push(
      rotationTrack(`lowerArm${side}` as BoneName, duration, () => new THREE.Euler(-elbowBend, 0, 0)),
    );
  }

  // Torso: forward lean, a small counter-twist, and the double-bounce bob.
  tracks.push(
    rotationTrack("spine", duration, (p) => new THREE.Euler(lean, Math.sin(p * TAU) * 0.05, 0)),
  );
  tracks.push(
    rotationTrack("chest", duration, (p) => new THREE.Euler(lean * 0.4, -Math.sin(p * TAU) * 0.08, 0)),
  );
  tracks.push(
    rotationTrack("hips", duration, (p) => new THREE.Euler(0, Math.sin(p * TAU) * 0.06, Math.sin(p * TAU) * 0.03)),
  );
  tracks.push(
    positionTrack("hips", duration, HIPS_REST, (p) =>
      // Two bounces per stride cycle — one per footfall.
      new THREE.Vector3(0, Math.abs(Math.sin(p * TAU)) * bob - bob * 0.5, 0),
    ),
  );

  return new THREE.AnimationClip(name, duration, tracks);
}

/** Standing: breathing, a slow weight shift, arms settled at the sides. */
export function idleClip(): THREE.AnimationClip {
  const duration = 4;
  const tracks: THREE.KeyframeTrack[] = [];
  tracks.push(
    rotationTrack("spine", duration, (p) => new THREE.Euler(0.02 + Math.sin(p * TAU) * 0.018, 0, 0)),
  );
  tracks.push(
    rotationTrack("chest", duration, (p) => new THREE.Euler(Math.sin(p * TAU) * 0.022, 0, 0)),
  );
  tracks.push(
    rotationTrack("neck", duration, (p) => new THREE.Euler(-Math.sin(p * TAU) * 0.02, Math.sin(p * TAU * 0.5) * 0.06, 0)),
  );
  tracks.push(
    positionTrack("hips", duration, HIPS_REST, (p) => new THREE.Vector3(0, Math.sin(p * TAU) * 0.006, 0)),
  );
  for (const [side, sign] of [["L", 1], ["R", -1]] as const) {
    tracks.push(
      rotationTrack(`upperArm${side}` as BoneName, duration, (p) =>
        new THREE.Euler(Math.sin(p * TAU + sign) * 0.03, 0, sign * 0.08),
      ),
    );
    tracks.push(
      rotationTrack(`lowerArm${side}` as BoneName, duration, () => new THREE.Euler(-0.14, 0, 0)),
    );
    tracks.push(
      rotationTrack(`upperLeg${side}` as BoneName, duration, () => new THREE.Euler(0, 0, 0)),
    );
    tracks.push(
      rotationTrack(`lowerLeg${side}` as BoneName, duration, () => new THREE.Euler(-0.02, 0, 0)),
    );
  }
  return new THREE.AnimationClip("idle", duration, tracks);
}

/** One full stride cycle (two steps) at a natural walking cadence. */
export function walkClip(): THREE.AnimationClip {
  return gaitClip("walk", {
    duration: 1,
    swing: 0.55,
    kneeBend: 0.75,
    armSwing: 0.42,
    elbowBend: 0.28,
    lean: 0.05,
    bob: 0.035,
  });
}

/** Same phase structure as the walk, pushed harder and leaning in. */
export function runClip(): THREE.AnimationClip {
  return gaitClip("run", {
    duration: 0.7,
    swing: 0.95,
    kneeBend: 1.5,
    armSwing: 0.85,
    elbowBend: 1.15,
    lean: 0.2,
    bob: 0.07,
  });
}

/**
 * Metres covered per stride cycle (two steps), used to lock playback rate to
 * ground speed so the feet do not slide.
 *
 * These are tuned, not derived from the rig's leg swing. The geometric stride
 * of this armature is only ~0.8 m, but the controller walks at 4.6 m/s and
 * sprints at 7.8 m/s — deliberately brisk, game speeds rather than human ones.
 * Driving cadence off the geometric stride would spin the legs at nearly six
 * cycles a second. Instead the stride is set so cadence lands near two cycles
 * per second at full speed, which is roughly what a race-walker or sprinter
 * actually does, and the residual slip is absorbed by the (small) difference
 * between the animated and assumed stride.
 */
export const STRIDE_LENGTH = { walk: 2.4, run: 4.0 };

/** Playback rate is clamped to this range so no speed produces a blur. */
export const TIME_SCALE_RANGE = { min: 0.55, max: 2.2 };
