/**
 * Tamkang material library — the renderer-side half.
 *
 * The maps themselves are generated by `scripts/gen-materials.mjs` into
 * `public/materials/tamkang/`. This file records how each set is *used*: the
 * `tile` field is the real-world size in metres that one texture repeat covers,
 * so geometry can bake correct UVs instead of every mesh guessing a repeat
 * count. One texture object per material, no per-mesh clones, so the GPU only
 * ever holds one copy.
 */
export type TamkangMaterialId =
  | "kenan/stone-step"
  | "kenan/retaining-wall"
  | "kenan/old-wall"
  | "kenan/moss"
  | "kenan/wet-concrete"
  | "palace/red-wall"
  | "palace/green-roof-tile"
  | "palace/wood-column"
  | "palace/lattice-window"
  | "lantern/stone-slab"
  | "lantern/kerb"
  | "lantern/asphalt"
  | "lantern/sidewalk"
  | "lantern/tactile-paving"
  | "library/facade"
  | "library/glass"
  | "campus/grass"
  | "campus/soil"
  | "campus/plaza-tile"
  | "campus/bronze";

export type TamkangMaterialSpec = {
  /** Metres of real surface covered by one texture repeat. */
  tile: number;
  /** Whether an ambient-occlusion map was generated for this set. */
  ao: boolean;
  /** Extra roughness offset applied on top of the roughness map. */
  roughnessBias?: number;
  metalness?: number;
  /** How strongly this surface reacts to the `wet` / after-rain preset. */
  wetResponse?: number;
  note: string;
};

export const TAMKANG_MATERIALS: Record<TamkangMaterialId, TamkangMaterialSpec> = {
  // One repeat = two treads wide, so a 0.32 m tread reads at the right grain.
  "kenan/stone-step": { tile: 1.6, ao: true, wetResponse: 1, note: "克難坡石階" },
  "kenan/retaining-wall": { tile: 2.4, ao: false, wetResponse: 0.9, note: "護牆清水混凝土" },
  "kenan/old-wall": { tile: 2.8, ao: false, wetResponse: 0.8, note: "舊砌石牆" },
  "kenan/moss": { tile: 0.9, ao: false, wetResponse: 1, note: "青苔" },
  "kenan/wet-concrete": { tile: 2.2, ao: false, wetResponse: 1, note: "潮濕鋪面" },
  "palace/red-wall": { tile: 3.2, ao: true, wetResponse: 0.6, note: "宮燈教室紅牆" },
  "palace/green-roof-tile": { tile: 2.2, ao: true, metalness: 0.05, wetResponse: 0.7, note: "碧瓦" },
  "palace/wood-column": { tile: 2.6, ao: false, wetResponse: 0.4, note: "迴廊朱柱" },
  "palace/lattice-window": { tile: 2.4, ao: true, wetResponse: 0.2, note: "木格窗" },
  "lantern/stone-slab": { tile: 3.0, ao: true, wetResponse: 1, note: "宮燈大道石板" },
  "lantern/kerb": { tile: 1.6, ao: false, wetResponse: 0.9, note: "路緣石" },
  "lantern/asphalt": { tile: 4.0, ao: false, wetResponse: 1, note: "柏油車道" },
  "lantern/sidewalk": { tile: 2.4, ao: false, wetResponse: 0.9, note: "人行道連鎖磚" },
  "lantern/tactile-paving": { tile: 0.6, ao: false, wetResponse: 0.8, note: "導盲磚" },
  "library/facade": { tile: 6.0, ao: true, wetResponse: 0.5, note: "圖書館外牆面磚" },
  "library/glass": { tile: 4.4, ao: false, metalness: 0.35, wetResponse: 0.2, note: "玻璃帷幕" },
  "campus/grass": { tile: 3.4, ao: false, wetResponse: 0.5, note: "草地" },
  "campus/soil": { tile: 2.0, ao: false, wetResponse: 1, note: "裸土" },
  "campus/plaza-tile": { tile: 3.6, ao: true, wetResponse: 1, note: "廣場地磚" },
  "campus/bronze": { tile: 1.4, ao: false, metalness: 0.55, wetResponse: 0.6, note: "銅雕" },
};

export const TAMKANG_MATERIAL_IDS = Object.keys(TAMKANG_MATERIALS) as TamkangMaterialId[];

export type MapKind = "basecolor" | "normal" | "roughness" | "ao";

export function materialMapUrl(id: TamkangMaterialId, kind: MapKind): string {
  return `/materials/tamkang/${id}-${kind}.png`;
}

/**
 * Which maps to fetch at a given quality tier. Mobile loads colour + roughness
 * only: normal and AO maps are where the download and the VRAM go, and their
 * absence costs far less than dropping the whole library back to one texture.
 */
export function mapKindsForTier(tier: "high" | "low"): MapKind[] {
  return tier === "high" ? ["basecolor", "normal", "roughness", "ao"] : ["basecolor", "roughness"];
}

/** Flat URL list to hand to drei's useTexture, plus the index to read it back. */
export function materialLoadPlan(tier: "high" | "low"): {
  urls: string[];
  entries: { id: TamkangMaterialId; kind: MapKind; index: number }[];
} {
  const urls: string[] = [];
  const entries: { id: TamkangMaterialId; kind: MapKind; index: number }[] = [];
  for (const id of TAMKANG_MATERIAL_IDS) {
    for (const kind of mapKindsForTier(tier)) {
      if (kind === "ao" && !TAMKANG_MATERIALS[id].ao) continue;
      entries.push({ id, kind, index: urls.length });
      urls.push(materialMapUrl(id, kind));
    }
  }
  return { urls, entries };
}
